[package]
name = "lazarus"
version = "1.0.6"
edition = "2021"

[dependencies]
colored = "2.0"
run_script = "0.10"
sysinfo = "0.29"
chrono = "0.4"
dialoguer = "0.10"
winreg = "0.10"
ureq = "2.6"
serde_json = "1.0"

[build-dependencies]
winres = "0.1"