[package]
name = "lazarus"
version = "2.1.0"
edition = "2021"

[dependencies]
colored = "2.0"
run_script = "0.10"
sysinfo = "0.29"
chrono = "0.4"
dialoguer = "0.10"
# New dependency for Registry editing
winreg = "0.10"