[package]
name = "lazarus"
version = "2.0.0"
edition = "2021"

[dependencies]
colored = "2.0"
run_script = "0.10"
sysinfo = "0.29"
chrono = "0.4"
dialoguer = "0.10"
winreg = "0.10"
ureq = "2.6"          # For the Auto-Updater
serde_json = "1.0"    # For the Auto-Updater
snmp = "5.2"          # <--- THE NEW ADDITION for net.rs

[build-dependencies]
winres = "0.1"