[package]
name = "lazarus"
version = "2.0.1"
edition = "2021"

[dependencies]
colored = "2.0"
run_script = "0.10"
sysinfo = "0.29"
chrono = "0.4"
dialoguer = "0.10"
winreg = "0.10"
ureq = "2.6"          # For the Auto-Updater
serde_json = "1.0"    # For the Auto-Updater
snmp = "0.2"          # <--- CHANGE THIS from "5.2" to "0.2"

[build-dependencies]
winres = "0.1"